### ISSUE TITLE
Cmake can't find HDF5 correctly

### ISSUE THREAD

**Issue by chenghaojia2323** [zexxzhao/DJANGO#3]
After I install petsc, hdf5, boost to Linux position, I ran "export PETSC_DIR=...   export BOOST_ROOT=...    export HDF5_ROOT=..." with correct direction. But when I ran:
        "cmake . -B build \ # makefile will be placed in build
          -DDJANGO_BUILD_TYPE=RELEASE \ # Turn on the optimization and disable assert()
          -DCMAKE_VERBOSE_MAKEFILE=ON \ # Print the details of compilation commands
          -DCMAKE_INSTALL_PREFIX=<PATH/TO/INSTALLATION> # specify where to install"
it said that "Found serial HDF5 build, MPI HDF5 build required, try setting HDF5_DIR or HDF5_ROOT".

**Comment by zexxzhao** [comment]
It seems your HDF5 is not parallel. You can post the full `cmake` output here.

**Comment by chenghaojia2323** [comment]
I'm sure that I use command "--enable-parallel" when downloading HDF5.
Full issue is:

**CMake Warning at /usr/share/cmake-3.22/Modules/FindHDF5.cmake:745 (message):
  HDF5 found for language C is parallel but previously found language is not
  parallel.
Call Stack (most recent call first):
  CMakeLists.txt:74 (find_package)


CMake Error at CMakeLists.txt:78 (message):
  Found serial HDF5 build, MPI HDF5 build required, try setting HDF5_DIR or
  HDF5_ROOT


-- Configuring incomplete, errors occurred!
See also "/home/chj/winterResearch/DJANGO-main/build/CMakeFiles/CMakeOutput.log".
See also "/home/chj/winterResearch/DJANGO-main/build/CMakeFiles/CMakeError.log".**

**Comment by zexxzhao** [comment]
You have enabled other components besides C (C++, Fortran, or HL), which do not support parallel IO.

**Comment by chenghaojia2323** [comment]
So how can enable C components? I think I follow all the tutorial.

**Comment by zexxzhao** [comment]
You have enabled the C component, and it is parallel. What `cmake` is complaining about is the other components, which might be turned on during your installation.
- > **CMake Warning at /usr/share/cmake-3.22/Modules/FindHDF5.cmake:745 (message): HDF5 found for language C is parallel but previously found language is not parallel. Call Stack (most recent call first): CMakeLists.txt:74 (find_package)

You can paste your configuration here to provide more information.
```bash
./configure --prefix=<PATH/TO/INSTALLATION> --enable-parallel
```
If it still does not work, we need to take a look at `CMakeLists.txt`.

**Comment by chenghaojia2323** [comment]
After further checking the installation process, I found the solution: before running 
`cmake . -B build \ # Makefile will be placed in build
  -DDJANGO_BUILD_TYPE=RELEASE \ # Turn on the optimization and disable assert()
  -DCMAKE_VERBOSE_MAKEFILE=ON \ # Print the details of compilation commands
  -DCMAKE_INSTALL_PREFIX=<PATH/TO/INSTALLATION> # Specify where to install`
I should first delete the "build" file in "DJANGO" file.

By the way, to successfully run the installation process, it must "git clone" the "DJANGO" file, instead of directly downloading the zip file.
